# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleasePoc < Formula
  desc ""
  homepage "https://github.com/nityanandagohain/gorelease_poc"
  version "0.1.10"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nityanandagohain/gorelease_poc/releases/download/v0.1.10/gorelease_poc_Darwin_x86_64.zip"
    sha256 "ea4d147dc7852fe39ce586648015d9bc2b086d9bef8836eb28f4e7890c7d7c65"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nityanandagohain/gorelease_poc/releases/download/v0.1.10/gorelease_poc_Linux_x86_64.zip"
      sha256 "d00d016c938a592ffe6463a97724369a51b636303b8ed4842a48a3105a18d81f"
    end
  end

  def install
    bin.install "gorelease_poc"
  end

  test do
    system "#{bin}/gorelease_poc --version"
  end
end
